/*
Generated By HoudiniSolverGenerator
Author: MuGdxy https://github.com/MuGdxy
*/

#include <OP/OP_OperatorTable.h>
#include <OP/OP_Operator.h>
#include <DOP/DOP_Operator.h>
#include <UT/UT_DSOVersion.h>
#include <SIM/SIM_Utils.h>
#include "SIM__EXAMPLE_SOLVER_.h"

void initializeSIM(void*)
{
    IMPLEMENT_DATAFACTORY(SIM__EXAMPLE_SOLVER_);
}


